In [1]:
import pandas as pd
import numpy as np

In [2]:
df1= pd.read_csv('fills.csv')
df2= pd.read_csv('settlepx_updated.csv')
pd.Series(df2['sym']).is_unique
# check if column of dataframe are unique to avoid descrepancy

False

In [3]:
# Dropping the outright postions to take only strategies into account 
brr=[]
k=0
for i in df1.sym:
    
    if '-' not in i and '+' not in i and ':' not in i:
            df1.drop([k],inplace=True)
    k+=1


In [4]:
# Format for mapping strategies with profit and loss
from collections import defaultdict
def default():
    return [0,0]
strat=defaultdict(default)

# print (strat[df1.sym[i]][1])


In [5]:
df1

date                  time exchange                   sym side  \
12     15.4.21  0D20:51:54.608156361      CME        GE:PB M3-M4-M5    B   
25     15.4.21  0D20:45:55.171559281      CME        GE:PB M3-M4-M5    S   
38     15.4.21  0D20:20:04.445186161      CME        GE:PB M3-M4-M5    S   
39     15.4.21  0D20:15:57.468748643      CME            SR3H2-GEH2    S   
45     15.4.21  0D20:15:32.028393411      CME            SR3M2-GEM2    B   
...        ...                   ...      ...                   ...  ...   
58437  13.4.21  0D06:33:17.895303000      ICE  SO3:FBUT:H25+M25+U25    S   
58441  13.4.21  0D06:33:08.791297000      ICE  SO3:FBUT:H25+M25+U25    S   
58445  13.4.21  0D06:33:07.039311000      ICE  SO3:FBUT:H25+M25+U25    S   
58449  13.4.21  0D06:33:05.263078000      ICE  SO3:FBUT:H25+M25+U25    S   
58453  13.4.21  0D06:33:03.759399000      ICE  SO3:FBUT:H25+M25+U25    S   

       quantity  price     wqp         trader   account  src  
12            5  -1.75   -8.75       CSCHMIDT  ARB01057  HFT  
25            5  -2.00  -10.00       CSCHMIDT  ARB01057  HFT  
38            4  -2.00   -8.00       CSCHMIDT  ARB01057  HFT  
39            4  14.50   58.00         CA1057  ARB01057  HFT  
45            7  15.50  108.50         CA1057  ARB01057  HFT  
...         ...    ...     ...            ...       ...  ...  
58437        76   0.00    0.00  amarkantkumar  ARB02357  HFT  
58441       100   0.00    0.00  amarkantkumar  ARB02357  HFT  
58445       100   0.00    0.00  amarkantkumar  ARB02357  HFT  
58449       100   0.00    0.00  amarkantkumar  ARB02357  HFT  
58453       100   0.00    0.00  amarkantkumar  ARB02357  HFT  

[6160 rows x 11 columns]

In [6]:
df2.dropna(inplace=True)

In [7]:
#Debugging
# for i in df1.index:
#     if df1.sym[i]=='SONH23-SONM23':
#         print (strat[df1.sym[i]][1])


In [8]:
k1=0
print (len(df1.index))
for i in df1.index:
#     print (df1.sym[i])
    if(df1.side[i]=='B'):
        
        strat[df1.sym[i]][0]+=df1.quantity[i]
        strat[df1.sym[i]][1]-=df1.quantity[i]*df1.price[i]
        
    else:
    
        strat[df1.sym[i]][0]-=df1.quantity[i]
        strat[df1.sym[i]][1]+=df1.quantity[i]*df1.price[i]
        
    
            
    

    

6160


In [9]:
for i in strat:
    if(strat[i][0]>0):
        
        if len(df2[df2['sym']==i]['settlepx'].values)>0:
            k3=df2[df2['sym']==i]['settlepx'].values
            strat[i][1]+=(strat[i][0]*k3[0])
            print (k3,strat[i][1])
#         else:
#             strat[i][1]+=0

            

            

            

[0. 0.] 6.0
[9994.5 9994.5] 48.0
[19.5 19.5] -0.5
[0.01 0.01] -1.6653345369377348e-16
[1. 1.] 0.5
[0. 0.] -1199.3024999999998
[14.5 14.5] 65.0
[5.75 5.75] 8.5
[0.095 0.095] 0.010000000000000009
[0.01 0.01] 0.23999999999999996
[1.25 1.25] -15.5
[99.74708 99.74708 99.74708 99.74708] 0.6372899999969377
[14.5 14.5] 71.5
[0.045 0.045 0.045] 0.1299999999999999
[0.02 0.02 0.02] -0.18500000000000005
[1.5 1.5] 12.5
[0.09 0.09 0.09] 0.0
[0.065 0.065 0.065] -1.6400000000000023
[0.075] 0.0
[0.055 0.055] 0.8049999999999997
[0.105 0.105] 0.014999999999998792
[0.065 0.065 0.065] -2.085000000000001
[9929.5 9929.5] 88.0
[9978.25 9978.25] 15.0
[0.065 0.065 0.065] -0.6699999999999999
[0.075 0.075] 0.30000000000000004
[0.065] -0.025000000000000022
[0.1 0.1] -0.12499999999999867
[6.5 6.5] -329.0
[5.5 5.5] 0.0
[16. 16.] -16.5
[4. 4.] -17.5
[0.05 0.05 0.05] -0.15000000000000124
[0. 0.] -498.86999999999995
[0.01 0.01] -0.4099999999999999
[0.01 0.01] 0.19
[0.1025 0.1025] -0.2250000000000003
[7.5 7.5] -402.0
[4

In [10]:
print (strat['SNAU22-SNAZ22'])

[75, -6.000000000000001]


In [11]:
strat

defaultdict(<function __main__.default()>,
            {'GE:PB M3-M4-M5': [6, 6.0],
             'SR3H2-GEH2': [-24, 295.0],
             'SR3M2-GEM2': [-161, 2579.5],
             'SR1U1-ZQU1': [-15, 70.0],
             'SR1X1-ZQX1': [-20, 80.0],
             'SR3:AB 01Y M1': [29, 48.0],
             'SF1U1-SF1V1': [-29, 0.0],
             'GE:PK 01Y M3': [0, -17.5],
             'GE:PK 01Y M4': [-21, 290.0],
             'SR3Z2-GEZ2': [-104, 2122.5],
             'SR1N1-ZQN1': [-10, 50.0],
             'SR3Z1-GEZ1': [101, -0.5],
             'SR1M1-ZQM1': [-6, 30.0],
             'SF1K1-SF1M1': [15, -1.6653345369377348e-16],
             'SR1K1-SR1M1': [64, 0.5],
             'SF1J1-SF1K1': [-71, 0.91],
             'SF3:PACK:M21': [12, -1199.3024999999998],
             'SR3M1-GEM1': [15, 65.0],
             'GE:FB 05Y M1': [-29, 147.0],
             'GE:FB 03Y M1': [-19, 66.5],
             'GE:PK 01Y M5': [-26, 310.0],
             'GE:PK 01Y M1': [-10, -5.0],
             'SR1J1-